import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "node:fs";
import path from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const dir = "dist";
if (!fs.existsSync(dir)) {
	fs.mkdirSync(dir);
}

const copyToDist = () => {
	fs.copyFileSync("manifest.json", path.join(dir, "manifest.json"));
	if (fs.existsSync("styles.css")) {
		fs.copyFileSync("styles.css", path.join(dir, "styles.css"));
	}
};

const plugin = {
	name: "copy-manifest",
	setup(build) {
		build.onEnd(() => {
			copyToDist();
			console.log("Copied manifest and styles to dist/");
		});
	},
};

const castv2PatchPlugin = {
	name: "castv2-patch",
	setup(build) {
		build.onResolve({ filter: /proto(\.js)?$/ }, (args) => {
			if (
				args.path.includes("proto") &&
				args.resolveDir.includes("castv2")
			) {
				console.log(`Patching proto in ${args.resolveDir}`);
				return {
					path: path.join(
						process.cwd(),
						"src/lib/castv2-proto-patch.ts"
					),
				};
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod,
	plugins: [plugin, castv2PatchPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
